/* =====================================================================
   GLOBAL CONFLICT MONITOR v3 — EXPANDED DATABASE (+60 zones → 100 total)
   Additional theaters compiled from: Crisis Group CrisisWatch (Sep 2026),
   HRW World Report 2026, ACLED, UN OCHA, Reuters, AP, Al Jazeera.
   Minor zones carry one briefing item each; figures are estimates.
   ===================================================================== */

CONFLICTS.push(
  /* ---------- EUROPE ---------- */
  { id:"ukraine-east", name:"Ukraine — Donbas Front", region:"Eastern Europe", lat:48.0, lon:38.0, cat:"war", intensity:4, status:"Grinding assault",
    since:"2014 (full-scale 2022)", casualties:"Heaviest attrition of the war", displaced:"Front-line towns emptied",
    parties:["Russia","Ukraine"],
    summary:"The war's bloodiest axis. Russian forces press slow, costly assaults toward Pokrovsk and around Dobropillia while Ukraine counterattacks; artillery and glide-bombs flatten the remaining front-line towns.",
    news:[{date:"2026-09-26",src:"Ukrinform / Azov",text:"Defense Forces continue to hold the Dobropillia sector as Russian assaults grind forward at heavy cost."}]},
  { id:"blacksea", name:"Black Sea Maritime War", region:"Black Sea · maritime", lat:44.5, lon:33.0, cat:"flashpoint", intensity:2, status:"Active",
    since:"2022", casualties:"Dozens of vessels hit on both sides", displaced:"—",
    parties:["Ukraine","Russia","Merchant shipping"],
    summary:"A live naval war: Ukrainian sea-drones hunt the Black Sea Fleet while Russia strikes Odesa-region ports and grain ships; insurers treat the northwestern Black Sea as a war-risk zone.",
    news:[{date:"2026-09-15",src:"Shipping / media",text:"Port and grain-infrastructure strikes around Odesa continue as Ukraine keeps hitting naval targets with sea-drones."}]},
  { id:"nato-russia", name:"Russia–NATO Shadow War", region:"Europe · Baltics", lat:56.0, lon:22.0, cat:"flashpoint", intensity:2, status:"Persistent",
    since:"2014 (intensified 2022)", casualties:"—", displaced:"—",
    parties:["Russia","NATO member states"],
    summary:"Sabotage, arson, GPS jamming, airspace violations and severed subsea cables — Europe's grey-zone war runs daily beneath the headlines, with NATO citing cognitive-warfare doctrine as the battlefield expands to 'society itself'.",
    news:[{date:"2026-09-20",src:"Terrorism Watch / NATO",text:"NATO analyses cite an Indian military paper on cognitive warfare as hybrid incidents across Europe keep accumulating."}]},
  { id:"belarus-poland", name:"Belarus–Poland Border War", region:"Eastern Europe", lat:52.9, lon:23.7, cat:"flashpoint", intensity:1, status:"Simmering",
    since:"2021", casualties:"Dozens of migrant deaths recorded", displaced:"—",
    parties:["Belarus","Poland / EU","Migrant routes"],
    summary:"Minsk keeps weaponising migrant flows against the EU's eastern flank; Poland's border barrier is a permanent standoff line with pushbacks, deaths and periodic sabre-rattling.",
    news:[{date:"2026-09-10",src:"Trackers",text:"Hybrid pressure at the Belarus–Poland border persists with attempted crossings and electronic interference."}]},
  { id:"kosovo", name:"Kosovo–Serbia Standoff", region:"Balkans", lat:42.6, lon:20.9, cat:"flashpoint", intensity:1, status:"Frozen",
    since:"2008 declaration", casualties:"—", displaced:"—",
    parties:["Kosovo","Serbia","KFOR / EULEX"],
    summary:"Dialogue stalls while NATO's KFOR keeps the peace. Northern Kosovo remains the flashpoint: barricades, attacks on police and elections boycotts recur under heavy international guard.",
    news:[{date:"2026-09-01",src:"Crisis Group CrisisWatch",text:"KFOR deployments hold the fragile status quo as Pristina–Belgrade dialogue remains deadlocked."}]},
  { id:"bosnia", name:"Bosnia — Secession Crisis", region:"Balkans", lat:43.9, lon:18.2, cat:"flashpoint", intensity:2, status:"Deteriorating",
    since:"1995 Dayton order under strain", casualties:"—", displaced:"—",
    parties:["Republika Srpska leadership","Bosnian state institutions","EUFOR / OHR"],
    summary:"Milorik Dodik's Republika Srpska keeps testing secessionist red lines — parallel institutions, referendum rhetoric and sanctions — while EUFOR patrols the country's most dangerous political crisis since the 1990s war.",
    news:[{date:"2026-09-10",src:"Trackers",text:"Secessionist brinkmanship continues; EUFOR maintains its deterrent presence amid stalled state-level governance."}]},
  { id:"moldova", name:"Moldova — Transnistria & Hybrid Pressure", region:"Eastern Europe", lat:47.2, lon:28.8, cat:"flashpoint", intensity:1, status:"Watch",
    since:"1992 (Transnistria)", casualties:"—", displaced:"—",
    parties:["Moldova","Transnistrian separatists","Russian garrison"],
    summary:"Chișinău walks a tightrope between EU integration and Russian hybrid pressure — energy coercion, disinformation and the frozen garrison in Transnistria — with every election treated as a national-security event.",
    news:[{date:"2026-09-10",src:"Crisis Group CrisisWatch",text:"Hybrid pressure on Moldova's pro-EU course persists; Transnistria stays frozen but armed."}]},

  /* ---------- MIDDLE EAST / NORTH AFRICA ---------- */
  { id:"saudi-houthi", name:"Saudi Arabia — Houthi Frontier", region:"Arabian Peninsula", lat:16.9, lon:42.6, cat:"flashpoint", intensity:2, status:"Alert",
    since:"2015 (re-ignited 2026)", casualties:"—", displaced:"—",
    parties:["Saudi Arabia","Houthis"],
    summary:"Flagged by CrisisWatch as a September conflict risk: Houthi projectiles reached Jazan for the first time in years, reminding Riyadh that its southern frontier is inside the Iran war's blast radius.",
    news:[{date:"2026-09-12",src:"Saudi Civil Defense",text:"Houthi projectile hits Al-Tuwal in Jazan, wounding two and damaging a mosque; shelter alerts briefly raised."}]},
  { id:"syria-israel", name:"South Syria — Israeli Incursion Zone", region:"Middle East", lat:32.9, lon:35.9, cat:"flashpoint", intensity:2, status:"Occupied buffer",
    since:"Dec 2024", casualties:"Dozens killed in strikes and clashes", displaced:"Quneitra & Deraa villages displaced",
    parties:["Israel","Syrian transitional authorities","Local armed groups"],
    summary:"After the old regime fell, Israeli forces seized a buffer zone deep into southern Syria and keep striking weapons shipments; negotiations over disengagement stall while the Iran war reshapes the board.",
    news:[{date:"2026-09-10",src:"Trackers",text:"Israeli operations continue in the southern Syria buffer zone as disengagement talks remain stalled."}]},
  { id:"turkey-syria", name:"Turkey–SDF Frontier", region:"Middle East", lat:36.7, lon:38.0, cat:"flashpoint", intensity:2, status:"Volatile",
    since:"2016 (Turkish operations)", casualties:"Dozens killed in 2026 strikes", displaced:"—",
    parties:["Turkey","SDF / Kurdish-led forces","Syrian transitional state"],
    summary:"Ankara keeps drones over northeast Syria, pressing the Kurdish-led SDF as it negotiates integration into Syria's new order; every strike risks pulling the US garrison into the crossfire.",
    news:[{date:"2026-09-05",src:"Trackers",text:"Turkish drone strikes on SDF-linked targets persist as integration talks between Damascus and the Kurdish administration drag."}]},
  { id:"yemen-south", name:"South Yemen — STC Separatism", region:"Arabian Peninsula", lat:12.8, lon:45.0, cat:"flashpoint", intensity:1, status:"Simmering",
    since:"2017", casualties:"—", displaced:"—",
    parties:["Southern Transitional Council","Internationally recognized government","Saudi/UAE patrons"],
    summary:"Beneath the Houthi war, the south's secessionist STC consolidates control from Aden to Hadramawt, kept in check only by its Gulf patrons' rival interests.",
    news:[{date:"2026-09-01",src:"Trackers",text:"STC consolidation continues in Aden and Hadramawt as the internationally recognized government weakens."}]},
  { id:"iran-sistan", name:"Iran — Sistan-Baluchestan", region:"Middle East", lat:28.9, lon:60.9, cat:"terror", intensity:1, status:"Active",
    since:"2010s", casualties:"Dozens killed in 2026 attacks and executions", displaced:"—",
    parties:["Jaish al-Adl","Iran (IRGC)"],
    summary:"Jaish al-Adl ambushes IRGC patrols and police posts in Iran's poorest province; Tehran answers with executions — a low-burn insurgency on the edge of the wider Iran war.",
    news:[{date:"2026-09-10",src:"Trackers",text:"Jaish al-Adl hit-and-run attacks on security forces continue along the Pakistan border belt."}]},
  { id:"iranian-kurdistan", name:"Iranian Kurdistan Front", region:"Middle East", lat:35.5, lon:46.5, cat:"flashpoint", intensity:1, status:"Watch",
    since:"1979", casualties:"—", displaced:"—",
    parties:["Iranian-Kurdish opposition","Iran / IRGC","Iraq-based bases"],
    summary:"US-Israeli planning reportedly considered mobilising Iranian-Kurdish opposition as the Iran war deepened; Tehran keeps striking their bases inside Iraq — a dormant front that 2026 has re-energised.",
    news:[{date:"2026-03-06",src:"The Guardian",text:"US and Israel weigh mobilising Iranian-Kurdish opposition as airstrikes hit the Iran–Iraq border."}]},
  { id:"westernsahara", name:"Western Sahara", region:"North Africa", lat:24.5, lon:-12.5, cat:"flashpoint", intensity:1, status:"Low-level",
    since:"1975", casualties:"—", displaced:"Sahrawi refugee camps in Algeria",
    parties:["Morocco","Polisario Front","MINURSO"],
    summary:"Polisario's low-level harassment of Moroccan positions east of the berm continues under a deadlocked UN process, while great-power recognition politics reshape the file.",
    news:[{date:"2026-09-01",src:"Crisis Group CrisisWatch",text:"Low-intensity Polisario actions persist east of the berm; MINURSO mandate renewed amid stalemate."}]},

  /* ---------- AFRICA ---------- */
  { id:"sudan-darfur", name:"Sudan — Darfur Front", region:"East Africa", lat:13.6, lon:25.3, cat:"civil", intensity:4, status:"Critical",
    since:"Apr 2023", casualties:"Tens of thousands killed in Darfur since 2023", displaced:"Millions across Darfur",
    parties:["SAF","RSF","Darfuri armed movements"],
    summary:"The Darfur siege grinds on: RSF encirclement of El Fasher, mass-casualty strikes on displacement camps and aid corridors collapsing — the epicentre of the world's largest displacement crisis.",
    news:[{date:"2026-09-15",src:"UN OCHA",text:"IOM reports 1,000+ newly displaced in North Darfur as security deteriorates around El Fasher; aid access keeps shrinking."}]},
  { id:"ethoromia", name:"Ethiopia — Oromia / OLA Insurgency", region:"Horn of Africa", lat:8.5, lon:37.5, cat:"civil", intensity:2, status:"Active",
    since:"2018", casualties:"Thousands killed since 2021", displaced:"Hundreds of thousands in western Oromia",
    parties:["ENDF","Oromo Liberation Army"],
    summary:"The OLA insurgency in western and southern Oromia simmers through peace-talk dead-ends, drone strikes and reprisals — Ethiopia's third front while Tigray and Amhara burn.",
    news:[{date:"2026-09-10",src:"ACLED",text:"OLA–ENDF clashes and drone operations persist across western Oromia as talks remain frozen."}]},
  { id:"chad", name:"Chad — Sudan Spillover", region:"Central Africa", lat:12.1, lon:15.0, cat:"flashpoint", intensity:2, status:"Strained",
    since:"2023 spillover", casualties:"Cross-border raids killed dozens in 2026", displaced:"800,000+ Sudanese refugees hosted",
    parties:["Chad","Sudanese actors","Lake Chad jihadist groups"],
    summary:"Chad hosts nearly a million Sudanese refugees while Sudan's war licks its borders and jihadists probe the Lake Chad basin — a triple crisis testing Africa's most coup-prone corridor.",
    news:[{date:"2026-09-10",src:"UN OCHA",text:"Refugee flows from Darfur keep arriving in eastern Chad as cross-border incidents multiply."}]},
  { id:"car", name:"Central African Republic", region:"Central Africa", lat:5.5, lon:20.5, cat:"civil", intensity:2, status:"Active",
    since:"2012", casualties:"Hundreds killed in 2026 incidents", displaced:"900,000+ displaced",
    parties:["Government + Wagner/Africa Corps","CPC rebel coalition","MINUSCA (drawn down)"],
    summary:"The CPC coalition keeps ambushing towns and supply routes while Russian-linked mercenaries and government forces hold the cities; with MINUSCA drawing down, civilians lose their last shield.",
    news:[{date:"2026-09-10",src:"Crisis Group CrisisWatch",text:"CPC attacks on towns and corridors continue as the UN drawdown accelerates."}]},
  { id:"guinea", name:"Guinea — Junta & Repression", region:"West Africa", lat:10.5, lon:-12.0, cat:"flashpoint", intensity:1, status:"Repressive",
    since:"2021 coup", casualties:"Dozens killed in protest crackdowns", displaced:"—",
    parties:["Junta (CNRD)","Opposition / civil society"],
    summary:"The Doumbouya junta rules by decree, silencing media and opposition while promising elections — Guinea's mineral wealth can't mask a slow-motion political crisis.",
    news:[{date:"2026-09-10",src:"HRW",text:"Forced disappearances and media shutdowns continue under the junta's transition timetable."}]},
  { id:"benin", name:"Benin — Jihadist Spillover", region:"West Africa", lat:10.3, lon:2.3, cat:"terror", intensity:1, status:"Spreading",
    since:"2021", casualties:"Dozens of soldiers and civilians killed", displaced:"Thousands in the north",
    parties:["JNIM / IS-Sahara elements","Beninese forces"],
    summary:"Jihadist violence has crossed from Burkina Faso into Benin's W National Park region — raids, IEDs and recruitment pushing the coastal states into the Sahel war's orbit.",
    news:[{date:"2026-09-10",src:"ACLED",text:"Attacks attributed to jihadist groups persist in Benin's northern border parks as coastal West Africa militarises."}]},
  { id:"senegal", name:"Senegal — Casamance", region:"West Africa", lat:12.55, lon:-16.2, cat:"flashpoint", intensity:1, status:"Fragile peace",
    since:"1982", casualties:"—", displaced:"Tens of thousands still displaced",
    parties:["MFDC factions","Senegal"],
    summary:"Africa's oldest civil war is nearly quiet but not dead: disarmament stalls, factionalised MFDC remnants and landmine belts keep Casamance's peace reversible.",
    news:[{date:"2026-09-10",src:"Trackers",text:"Disarmament of MFDC factions proceeds slowly; sporadic banditry keeps Casamance fragile."}]},
  { id:"burundi", name:"Burundi — Rebel Raids", region:"East Africa", lat:-3.3, lon:29.9, cat:"civil", intensity:1, status:"Simmering",
    since:"2015 crisis; RED-Tabara raids", casualties:"Dozens killed in cross-border raids", displaced:"—",
    parties:["RED-Tabara","Burundi (FDNB)","DRC-based sanctuaries"],
    summary:"RED-Tabara raids from eastern Congo hit Burundi's border villages; the government answers with crackdowns and cross-border operations that feed the cycle.",
    news:[{date:"2026-09-10",src:"Trackers",text:"Cross-border raids and security crackdowns continue along the Burundi–DRC frontier."}]},
  { id:"zambia", name:"Zambia — Election Crisis", region:"Southern Africa", lat:-15.4, lon:28.3, cat:"flashpoint", intensity:2, status:"Deteriorated (CrisisWatch)",
    since:"Aug 2026 elections", casualties:"At least one polling agent killed; dozens arrested", displaced:"—",
    parties:["Government (UPND)","Opposition alliance","Security forces"],
    summary:"Zambia's usually peaceful democracy cracked: the August 2026 elections were marred by attacks on polling staff, stolen ballots, a suspended count and the army interrogating the opposition leader — CrisisWatch lists Zambia among August's deteriorated situations.",
    news:[{date:"2026-08-16",src:"Al Jazeera",text:"EU and SADC observers report intimidation, abductions and violence across five provinces; counting was suspended after attacks on polling staff and ballot theft."},
             {date:"2026-08-14",src:"AP",text:"Vote counting suspended then restarted under army deployment in Lusaka; opposition leader Brian Mundubile says he was interrogated by the army."}]},
  { id:"nigeria-middlebelt", name:"Nigeria — Middle Belt Killings", region:"West Africa", lat:9.5, lon:8.9, cat:"civil", intensity:2, status:"Chronic",
    since:"2010s", casualties:"Thousands killed in farmer–herder violence", displaced:"Hundreds of thousands",
    parties:["Armed herder militias","Farming communities","Criminal gangs"],
    summary:"Plateau, Benue and Kaduna bleed in a cycle of farm raids, village massacres and reprisals that kills as steadily as the northeast insurgency — with almost no accountability.",
    news:[{date:"2026-09-26",src:"CFR Nigeria Security Tracker",text:"Kidnappers abduct a traditional ruler in Pankshin, Plateau — the Middle Belt's kidnapping economy keeps growing."}]},
  { id:"cameroon-farnorth", name:"Cameroon — Far North / Lake Chad", region:"Central Africa", lat:10.6, lon:14.3, cat:"terror", intensity:2, status:"Active",
    since:"2014", casualties:"Hundreds killed in 2026 raids", displaced:"300,000+ in the Far North",
    parties:["ISWAP / Boko Haram","Cameroonian forces","Multinational JTF"],
    summary:"ISWAP raids fishing villages and military posts around Lake Chad while suicide bombings recur — Cameroon's forgotten front in the basin-wide jihadist war.",
    news:[{date:"2026-09-10",src:"ACLED",text:"ISWAP raids and IED attacks persist in Cameroon's Mayo-Sava and Logone-et-Chémir departments."}]},
  { id:"angola-cabinda", name:"Angola — Cabinda", region:"Central Africa", lat:-5.2, lon:12.2, cat:"civil", intensity:1, status:"Low-level",
    since:"1975", casualties:"—", displaced:"—",
    parties:["FLEC factions","Angola"],
    summary:"Africa's longest-running low-level insurgency: FLEC gunmen ambush troops in oil-rich Cabinda, an exclave whose revenue fuels Angola but whose people still demand independence.",
    news:[{date:"2026-09-10",src:"Trackers",text:"FLEC claims sporadic ambushes on security forces in Cabinda's forest belt."}]},
  { id:"guinea-bissau", name:"Guinea-Bissau — Coup Politics", region:"West Africa", lat:11.9, lon:-15.2, cat:"flashpoint", intensity:1, status:"Fragile",
    since:"1980 cycle of coups", casualties:"—", displaced:"—",
    parties:["Junta / political elite","ECOWAS"],
    summary:"The 'coup republic' staggers between delayed elections, dissolved parliaments and narco-money politics — West Africa's most volatile institutional vacuum.",
    news:[{date:"2026-09-10",src:"Crisis Group CrisisWatch",text:"Electoral calendar disputes and elite feuds keep Guinea-Bissau's transition on a knife edge."}]},
  { id:"tanzania", name:"Tanzania — Election Repression", region:"East Africa", lat:-6.8, lon:39.3, cat:"flashpoint", intensity:1, status:"Deteriorated",
    since:"Oct 2025 elections", casualties:"Dozens killed in protest crackdowns", displaced:"—",
    parties:["Government (CCM)","Opposition"],
    summary:"The disputed October 2025 elections and the exclusion of main opponents triggered crackdowns on protests; rights groups document abductions and lethal force as the October 2026 polls approach.",
    news:[{date:"2026-09-10",src:"HRW",text:"Abductions and protest deaths documented a year after the disputed vote; opposition activity remains constrained."}]},

  /* ---------- ASIA-PACIFIC ---------- */
  { id:"ttp-pakistan", name:"Pakistan — TTP Insurgency", region:"South Asia", lat:33.0, lon:71.0, cat:"terror", intensity:3, status:"Worsening",
    since:"2007", casualties:"1,000+ killed in 2025-26 attacks", displaced:"—",
    parties:["Tehrik-i-Taliban Pakistan","Pakistan security forces"],
    summary:"The TTP is at its deadliest in a decade — police stations, checkpoints and mosques targeted inside Pakistan — the engine behind Islamabad's confrontation with Kabul, which it accuses of sheltering the fighters.",
    news:[{date:"2026-09-17",src:"Al Jazeera",text:"An attack on a police facility in northwestern Pakistan kills at least 21; a TTP faction claims it, reigniting the Pakistan–Afghanistan fighting."}]},
  { id:"india-maoist", name:"India — Maoist Insurgency", region:"South Asia", lat:19.8, lon:81.5, cat:"civil", intensity:1, status:"Winding down",
    since:"1967", casualties:"Dozens killed in 2026 operations", displaced:"—",
    parties:["CPI-Maoist","Indian security forces"],
    summary:"India's decades-old Naxalite war is being squeezed out of Bastar under a 'zero-Maoist' campaign — ambushes and surrenders alternate as the insurgency's endgame plays out.",
    news:[{date:"2026-09-10",src:"Trackers",text:"Security-force operations and sporadic IED ambushes continue in the Bastar heartland."}]},
  { id:"manipur", name:"India — Manipur Ethnic War", region:"South Asia", lat:24.8, lon:93.9, cat:"civil", intensity:2, status:"Simmering",
    since:"May 2023", casualties:"250+ killed since 2023", displaced:"60,000+ still in relief camps",
    parties:["Meitei armed groups","Kuki-Zo armed groups","Indian forces"],
    summary:"The Meitei–Kuki divide remains a fortified, militarised stalemate: buffer zones, arms seizures and periodic gunfire while tens of thousands stay displaced and no political settlement exists.",
    news:[{date:"2026-09-10",src:"Trackers",text:"Tensions persist along the buffer zones; authorities keep arms-surrender drives alive amid sporadic incidents."}]},
  { id:"myanmar-rakhine", name:"Myanmar — Rakhine / Arakan Army", region:"Southeast Asia", lat:20.5, lon:93.2, cat:"civil", intensity:3, status:"AA offensive",
    since:"2023 AA offensive", casualties:"Thousands killed; whole towns emptied", displaced:"Hundreds of thousands, incl. Rohingya",
    parties:["Arakan Army","Junta","Rohingya civilians"],
    summary:"The Arakan Army has overrun most of Rakhine state, besieging junta bastions while Rohingya and Rakhine civilians flee by sea and land — a war within the war.",
    news:[{date:"2026-09-10",src:"Trackers",text:"AA consolidation continues as the junta holds coastal pockets and airstrikes displacement camps."}]},
  { id:"myanmar-karen", name:"Myanmar — Karen / Karenni Front", region:"Southeast Asia", lat:16.8, lon:97.6, cat:"civil", intensity:2, status:"Active",
    since:"1949 (renewed 2021)", casualties:"—", displaced:"Tens of thousands along the Thai border",
    parties:["KNU / KNPP + PDFs","Junta"],
    summary:"Ethnic forces and PDFs contest the Thai-border highlands; junta airstrikes burn villages while refugee flows inch across the Moei river into Thailand.",
    news:[{date:"2026-09-10",src:"Trackers",text:"KNU–KNPP operations and junta airstrikes continue along the border belt."}]},
  { id:"bangladesh", name:"Bangladesh — Post-Uprising Transition", region:"South Asia", lat:23.8, lon:90.4, cat:"flashpoint", intensity:2, status:"Fragile",
    since:"Jul 2024 uprising", casualties:"1,400+ killed in 2024 unrest; sporadic 2026 violence", displaced:"—",
    parties:["BNP government","Banned Awami League","Student movements"],
    summary:"The February 2026 elections — free but held with the Awami League banned — returned the BNP and 'familiar equilibrium'. Political violence, labour unrest and a hostile India relationship keep the transition fragile.",
    news:[{date:"2026-05-28",src:"Carnegie",text:"'Bangladesh's Unfinished Revolution': the AL's exclusion lays the groundwork for the next crisis as the BNP confronts strikes and agitation."},
             {date:"2026-07-10",src:"Crisis Group",text:"Dhaka must manage reform pressure, a million Rohingya and a tense Myanmar border while normalising ties with India."}]},
  { id:"thaisouth", name:"Thailand — Deep South Insurgency", region:"Southeast Asia", lat:6.7, lon:101.0, cat:"terror", intensity:1, status:"Low-level",
    since:"2004", casualties:"Dozens killed in 2026 incidents", displaced:"—",
    parties:["BRN","Thailand"],
    summary:"The Malay-Muslim insurgency has quieted but not ended: sporadic bombings and shootings persist while peace dialogue drifts — 7,000 dead since 2004.",
    news:[{date:"2026-09-10",src:"ACLED",text:"Low-frequency BRN attacks continue in Pattani, Yala and Narathiwat."}]},
  { id:"philippines", name:"Philippines — Dual Insurgency", region:"Southeast Asia", lat:12.5, lon:124.5, cat:"civil", intensity:1, status:"Winding down",
    since:"1969 (NPA); Abu Sayyaf remnants", casualties:"Dozens killed in 2026 clashes", displaced:"—",
    parties:["NPA","Abu Sayyaf remnants","AFP"],
    summary:"Marcos's 'whole-of-nation' push grinds the ageing communist insurgency toward its end, while Abu Sayyaf splinters survive on kidnapping in the Sulu archipelago.",
    news:[{date:"2026-09-10",src:"Trackers",text:"NPA skirmishes and the remnants' kidnapping economy persist in Mindanao and the Sulu Sea."}]},
  { id:"westpapua", name:"West Papua Insurgency", region:"Oceania", lat:-4.0, lon:136.5, cat:"civil", intensity:1, status:"Low-level",
    since:"1963", casualties:"Dozens killed annually", displaced:"Tens of thousands in the highlands",
    parties:["TPNPB / Free Papua Movement","Indonesia"],
    summary:"Separatist ambushes, hostage standoffs and Indonesian sweeps continue in Papua's highlands, largely invisible to the world — with aid workers and pilots among the victims.",
    news:[{date:"2026-09-10",src:"Trackers",text:"TPNPB attacks and Indonesian security operations persist in the central highlands."}]},
  { id:"northkorea", name:"Korean Peninsula Standoff", region:"East Asia", lat:38.9, lon:126.5, cat:"flashpoint", intensity:2, status:"Chronic",
    since:"1953 armistice", casualties:"—", displaced:"—",
    parties:["North Korea","South Korea","United States"],
    summary:"Kim's missile tests, nuclear doctrine and 'hostile two-states' posture meet scaled-up US–ROK drills on a peninsula where any miscalculation escalates in minutes.",
    news:[{date:"2026-09-10",src:"Trackers",text:"Missile tests and allied exercises continue on their familiar escalatory rhythm."}]},
  { id:"indchina", name:"India–China Border Standoff", region:"Asia · Himalaya", lat:30.0, lon:88.0, cat:"flashpoint", intensity:1, status:"Managed",
    since:"2020 Galwan", casualties:"—", displaced:"—",
    parties:["India","China (PLA)"],
    summary:"After the 2020-22 standoffs, both sides keep tens of thousands of troops and hard infrastructure along the LAC — disengaged but never demilitarised.",
    news:[{date:"2026-09-10",src:"Trackers",text:"Patrolling arrangements hold while both armies deepen border infrastructure."}]},
  { id:"armenia-azerbaijan", name:"Armenia–Azerbaijan", region:"Caucasus", lat:39.7, lon:45.5, cat:"flashpoint", intensity:1, status:"Fragile peace",
    since:"1988 (2023 Karabakh war ended)", casualties:"—", displaced:"100,000+ Karabakh Armenians exiled",
    parties:["Armenia","Azerbaijan"],
    summary:"Post-war peace talks inch forward on border delimitation and the Zangezur corridor, but the South Caucasus balance rests on rival Russian, Turkish and Western guarantees.",
    news:[{date:"2026-09-10",src:"Crisis Group CrisisWatch",text:"Delimitation talks continue; sporadic border incidents keep the peace reversible."}]},
  { id:"tajik-afghan", name:"Tajik–Afghan Border", region:"Central Asia", lat:37.8, lon:70.5, cat:"flashpoint", intensity:1, status:"Watch",
    since:"2021 Taliban takeover", casualties:"Dozens killed in cross-border incidents", displaced:"—",
    parties:["Tajikistan","Taliban authorities","Militant groups"],
    summary:"Smuggling, militant crossings and Taliban-Tajik distrust keep the 1,300-km border armed to the teeth — with Russian bases watching Russia's soft southern underbelly.",
    news:[{date:"2026-09-10",src:"Trackers",text:"Cross-border shootings and smuggling incidents persist along the Panj river."}]},
  { id:"greece-turkey", name:"Aegean Standoff", region:"Eastern Mediterranean", lat:38.5, lon:25.5, cat:"flashpoint", intensity:1, status:"Managed",
    since:"1974", casualties:"—", displaced:"—",
    parties:["Greece","Turkey"],
    summary:"Islet sovereignty, airspace violations and Cyprus keep NATO's southeastern rivals in a permanent low-temperature standoff.",
    news:[{date:"2026-09-10",src:"Trackers",text:"Airspace incursions and naval shadowing continue despite dialogue mechanisms."}]},
  { id:"n-ireland", name:"Northern Ireland — Dissident Threat", region:"Western Europe", lat:54.6, lon:-6.3, cat:"flashpoint", intensity:1, status:"Low-level",
    since:"1998 Good Friday order", casualties:"—", displaced:"—",
    parties:["New IRA / dissident republicans","PSNI / MI5"],
    summary:"Dissident republican attacks on police and prisons persist at low level; Stormont's restored institutions remain the best bulwark against a return to the Troubles.",
    news:[{date:"2026-09-10",src:"Trackers",text:"PSNI threat level remains 'severe' as dissident plots are disrupted."}]},
  { id:"png", name:"Papua New Guinea — Highlands Violence", region:"Oceania", lat:-6.0, lon:144.0, cat:"criminal", intensity:1, status:"Chronic",
    since:"Decades", casualties:"Hundreds killed annually in tribal fighting", displaced:"—",
    parties:["Tribal militias","PNG state"],
    summary:"Automatic-weapon tribal warfare, sexual violence and weak policing make the Highlands one of the Pacific's deadliest forgotten conflicts.",
    news:[{date:"2026-09-10",src:"Trackers",text:"Tribal clashes and displacement recur in Enga and Hela provinces."}]},

  /* ---------- AMERICAS ---------- */
  { id:"colombia-catatumbo", name:"Colombia — Catatumbo Offensive", region:"South America", lat:8.1, lon:-72.8, cat:"criminal", intensity:3, status:"Acute",
    since:"Jan 2025 offensive", casualties:"Hundreds killed; 50,000+ displaced", displaced:"50,000+ displaced",
    parties:["ELN","FARC-EMC 33rd Front","Colombian state"],
    summary:"The ELN's war on the 33rd Front turned Catatumbo into Colombia's worst displacement crisis in years — coca fields, extortion and a 'total peace' policy in ruins.",
    news:[{date:"2026-09-10",src:"ACLED",text:"ELN–dissident fighting and state offensives keep Catatumbo's humanitarian emergency alive."}]},
  { id:"colombia-cauca", name:"Colombia — Cauca War", region:"South America", lat:2.7, lon:-76.8, cat:"criminal", intensity:2, status:"Worsening",
    since:"2023 escalation", casualties:"Hundreds killed since 2023", displaced:"Indigenous and Afro communities displaced",
    parties:["Dagoberto Ramos / EMC columns","Colombian state","Indigenous guard"],
    summary:"Dissident columns fight for the Pacific cocaine corridor through Cauca, bombing towns, recruiting minors and targeting the indigenous guard — the sharpest failure of 'paz total'.",
    news:[{date:"2026-09-10",src:"ACLED",text:"Car bombs, drone attacks and assassinations continue across Cauca's corridor."}]},
  { id:"mexico-michoacan", name:"Mexico — Michoacán Cartel War", region:"North America", lat:19.1, lon:-101.9, cat:"criminal", intensity:3, status:"Acute",
    since:"2006", casualties:"Thousands killed in recent years", displaced:"Towns displaced by CJNG advances",
    parties:["CJNG","Cárteles Unidos / Viagras","Mexican state"],
    summary:"CJNG's offensive through Tierra Caliente burns towns, hangs banners and displaces communities as lime and avocado economies fund the war — Mexico's hottest cartel front.",
    news:[{date:"2026-09-10",src:"Trackers",text:"CJNG advances and community self-defense mobilisation continue in Tierra Caliente."}]},
  { id:"mexico-chiapas", name:"Mexico — Chiapas Front", region:"North America", lat:16.5, lon:-92.3, cat:"criminal", intensity:2, status:"Worsening",
    since:"2021 escalation", casualties:"Hundreds killed", displaced:"Tens of thousands displaced",
    parties:["Sinaloa Cartel","CJNG","Local militias"],
    summary:"The Sinaloa–CJNG war now runs through Chiapas's migrant corridors: roadblocks, disappearances and displaced villages on Guatemala's doorstep.",
    news:[{date:"2026-09-10",src:"Trackers",text:"Cartel battles and migrant-route violence persist along the Frontera Comalapa corridor."}]},
  { id:"honduras", name:"Honduras — Gang Control", region:"Central America", lat:14.8, lon:-86.8, cat:"criminal", intensity:2, status:"State of exception",
    since:"2022 state of exception", casualties:"Thousands of homicides per year", displaced:"247,000+ internally displaced",
    parties:["Barrio 18 / MS-13","Honduran state"],
    summary:"Under a years-long state of exception, gangs still tax, kill and displace whole neighbourhoods of Tegucigalpa and San Pedro Sula — the engine feeding northbound migration.",
    news:[{date:"2026-09-10",src:"Trackers",text:"Extortion and displacement continue despite the prolonged state of exception."}]},
  { id:"jamaica", name:"Jamaica — Gang Emergency", region:"Caribbean", lat:18.0, lon:-76.8, cat:"criminal", intensity:1, status:"States of emergency",
    since:"Decades", casualties:"1,000+ murders per year", displaced:"—",
    parties:["Garrison gangs","Jamaican state"],
    summary:"Repeated states of emergency can't break the garrison system: murder rates among the world's highest, politics entwined with gangs, and Kingston's poor communities paying the price.",
    news:[{date:"2026-09-10",src:"Trackers",text:"States of public emergency continue across Kingston parishes."}]},
  { id:"peru-vraem", name:"Peru — VRAEM Remnants", region:"South America", lat:-12.0, lon:-73.7, cat:"terror", intensity:1, status:"Low-level",
    since:"1980s (remnant phase)", casualties:"Dozens killed annually", displaced:"—",
    parties:["Shining Path remnants","Peruvian forces"],
    summary:"The last Shining Path column guards coca corridors in the VRAEM valley, ambushing patrols and shooting down interdiction flights — a ghost of Peru's war.",
    news:[{date:"2026-09-10",src:"Trackers",text:"Ambushes and narco-flights persist in the VRAEM corridor."}]},
  { id:"brazil-rio", name:"Brazil — Rio's Criminal War", region:"South America", lat:-22.9, lon:-43.2, cat:"criminal", intensity:2, status:"Chronic",
    since:"Decades", casualties:"Thousands killed annually in police operations and gang wars", displaced:"—",
    parties:["Comando Vermelho","Milícias","Police"],
    summary:"Comando Vermelho, militias and armoured police operations fight block by block through Rio's favelas — with mass-casualty raids drawing international condemnation.",
    news:[{date:"2026-09-10",src:"Trackers",text:"Large-scale police operations and militia expansion continue across Greater Rio."}]},
  { id:"chile-mapuche", name:"Chile — Mapuche Conflict", region:"South America", lat:-38.7, lon:-72.6, cat:"flashpoint", intensity:1, status:"Simmering",
    since:"1990s", casualties:"Dozens killed since 2016", displaced:"—",
    parties:["Mapuche radical groups","Chilean state","Forestry firms"],
    summary:"Arson, land occupations and militarised policing continue in Araucanía, where ancestral land claims and forestry capital keep colliding.",
    news:[{date:"2026-09-10",src:"Trackers",text:"Arson attacks and militarised deployments persist in the Macrozona Sur."}]},
  { id:"bolivia", name:"Bolivia — Political Collapse", region:"South America", lat:-16.5, lon:-68.1, cat:"flashpoint", intensity:1, status:"Crisis",
    since:"2025 elections aftermath", casualties:"Dozens killed in 2025-26 unrest", displaced:"—",
    parties:["New government","MAS factions","Social movements"],
    summary:"Fuel shortages, dollar scarcity and a fractured MAS keep Bolivia in permanent street politics — blockades and protests testing the post-election government.",
    news:[{date:"2026-09-10",src:"Trackers",text:"Blockades over fuel and currency shortages recur as the new government seeks stabilisation."}]},
  { id:"guyana-essequibo", name:"Guyana–Venezuela Essequibo", region:"South America", lat:5.5, lon:-59.5, cat:"flashpoint", intensity:1, status:"Watch",
    since:"2023 claim escalation", casualties:"—", displaced:"—",
    parties:["Venezuela","Guyana","US Southern Command"],
    summary:"Caracas's claim over two-thirds of Guyana cooled after Maduro's capture but didn't die — oil-rich Essequibo stays garrisoned, drilled and disputed.",
    news:[{date:"2026-09-10",src:"Trackers",text:"The territorial claim persists rhetorically while Exxon-led drilling expands offshore."}]},
  { id:"cuba", name:"Cuba — Pressure Crisis", region:"Caribbean", lat:22.5, lon:-79.5, cat:"flashpoint", intensity:1, status:"Deteriorating",
    since:"2021 protests era", casualties:"—", displaced:"20%+ of the population has emigrated since 2020",
    parties:["Cuban state","Dissidents / emigrants","United States"],
    summary:"Blackouts, hunger-level shortages and political imprisonment fuel the largest emigration wave in Cuban history, while Washington's pressure campaign targets Havana directly.",
    news:[{date:"2026-09-20",src:"Rio Times",text:"Washington keeps pressure on Havana as the island's blackout and food crisis deepens."}]},
  { id:"nicaragua", name:"Nicaragua — Ortega Repression", region:"Central America", lat:12.6, lon:-85.5, cat:"flashpoint", intensity:1, status:"Authoritarian consolidation",
    since:"2018 crackdown", casualties:"355+ killed in 2018; ongoing political imprisonment", displaced:"200,000+ exiled",
    parties:["Ortega-Murillo state","Exiled opposition"],
    summary:"The Ortega-Murillo regime rules over emptied jails of former political prisoners — deported, stateless, exiled — with the Church, universities and NGOs dismantled.",
    news:[{date:"2026-09-10",src:"Trackers",text:"Political imprisonments and exile continue as the regime deepens institutional control."}]},

  /* ---------- MARITIME ---------- */
  { id:"gulf-guinea", name:"Gulf of Guinea Piracy", region:"West Africa · maritime", lat:2.5, lon:6.0, cat:"criminal", intensity:1, status:"Reduced but active",
    since:"2000s", casualties:"Dozens of kidnapped seafarers annually", displaced:"—",
    parties:["Nigerian pirate networks","Regional navies"],
    summary:"Kidnap-for-ransom piracy off Nigeria and Cameroon remains the world's most dangerous for seafarers, even as naval cooperation dents the numbers.",
    news:[{date:"2026-09-10",src:"IMB",text:"Kidnapping risk persists for vessels anchored off the Niger Delta and Bonny approaches."}]}
);

CONFLICTS.push(
  { id:"sudan-kordofan", name:"Sudan — Kordofan Front", region:"East Africa", lat:13.2, lon:30.2, cat:"civil", intensity:3, status:"Counter-offensive",
    since:"Apr 2023", casualties:"Hundreds killed in September fighting", displaced:"Fresh displacement from El Obeid axis",
    parties:["SAF","RSF","SPLM-N allies"],
    summary:"The war's mobile front: SAF counter-offensives retaking towns in North Kordofan against RSF-SPLM-N positions, drone wars over El Obeid, and strikes on displacement centres keeping the centre of the country ablaze.",
    news:[{date:"2026-09-17",src:"Sudan Tribune",text:"SAF says it recaptured 11 areas in North Kordofan; RSF drone waves hit Ad-Damazin and El Obeid, killing civilians."}]},
  { id:"ukraine-south", name:"Ukraine — Southern Front", region:"Eastern Europe", lat:47.4, lon:35.5, cat:"war", intensity:3, status:"Positional",
    since:"2022", casualties:"Constant attrition on the Zaporizhzhia–Kherson line", displaced:"—",
    parties:["Russia","Ukraine"],
    summary:"Russia presses limited offensives toward Orikhiv while Ukraine holds the line and strikes logistics across the Dnipro — the quieter but lethal half of the front.",
    news:[{date:"2026-09-21",src:"ISW",text:"Russian forces continue offensive operations west of and toward Orikhiv but do not advance; Ukrainian counterattacks hold."}]}
);

/* ---- extra arcs & flows ---- */
ARCS.push(
  { from:[51.0,36.0], to:[46.48,30.73], color:0xff5a4d, label:"Russia → Odesa port strikes" },
  { from:[12.5,-64.0], to:[10.5,-66.9], color:0x2dd4bf, label:"US Southern Spear → Venezuelan coast" }
);
FLOWS.push(
  { from:[10.5,-66.9], to:[7.1,-73.1], color:0x2dd4bf, label:"Venezuelans → Colombia" },
  { from:[8.0,32.5],  to:[3.5,32.5],  color:0x2dd4bf, label:"South Sudanese → Uganda" }
);

/* ---- curated tour (12 stops) ---- */
TOUR.length = 0;
TOUR.push("ukraine","sudan-darfur","iran","gaza","southsudan","ethiopia","drc","myanmar","pakafg","haiti","mexico","scs");

/* ---- extra wire items ---- */
TICKER.push(
  "16 AUG — ZAMBIA: counting suspended amid ballot theft and attacks; army interrogates opposition leader (AP)",
  "28 MAY — BANGLADESH: 'Unfinished Revolution' — banned Awami League fuels post-election confrontation (Carnegie)",
  "05 AUG — ETHIOPIA: CrisisWatch lists Ethiopia among deteriorated situations as Tigray war resumes",
  "10 SEP — BENIN: jihadist attacks spread in W National Park as coastal West Africa militarises (ACLED)"
);
